"""Initial migration

Revision ID: 006525b08092
Revises: 1864d8f8dd33
Create Date: 2024-03-14 09:35:07.502529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006525b08092'
down_revision = '1864d8f8dd33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('is_deceased', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dependents')
    # ### end Alembic commands ###
