"""Initial migration

Revision ID: 25952d84e65e
Revises: 8f51010eb1ad
Create Date: 2024-09-15 11:30:51.423543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25952d84e65e'
down_revision = '8f51010eb1ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('id_number',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.alter_column('id_number',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)

    # ### end Alembic commands ###
