"""Initial migration

Revision ID: 287ff5deebd6
Revises: b31dea726bf5
Create Date: 2024-03-14 09:59:31.468677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '287ff5deebd6'
down_revision = 'b31dea726bf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dependents', schema=None) as batch_op:
        batch_op.alter_column('relationship',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dependents', schema=None) as batch_op:
        batch_op.alter_column('relationship',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
