"""Initial migration

Revision ID: 33329a448ef4
Revises: 0f6f49001695
Create Date: 2024-03-19 09:23:12.764017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33329a448ef4'
down_revision = '0f6f49001695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('dependent_id', sa.Integer(), nullable=True),
    sa.Column('member_deceased', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('case_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cases')
    # ### end Alembic commands ###
