"""Initial migration

Revision ID: 402d2c2c22d5
Revises: 4853d0464914
Create Date: 2024-03-13 11:18:48.511093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '402d2c2c22d5'
down_revision = '4853d0464914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deceased', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('is_deceased')

    # ### end Alembic commands ###
