"""Initial migration

Revision ID: b31dea726bf5
Revises: 006525b08092
Create Date: 2024-03-14 09:47:33.578134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b31dea726bf5'
down_revision = '006525b08092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dependents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relationship', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dependents', schema=None) as batch_op:
        batch_op.drop_column('relationship')

    # ### end Alembic commands ###
